### ISSUE TITLE
Allow for multiple spaces and/or tabs on inline comments

### ISSUE THREAD

**Issue by chriscct7** [m1/Env#11]
It'd be nice if you could use more than 1 space and/or tabs before comments inline so that comments could be aligned in a long config file

Reported to https://github.com/josegonzalez/php-dotenv/issues/42 accidentally.

**Comment by m1** [comment]
Can look into but pretty busy with work atm, feel free to do a pull request though :smile:

**Comment by m1** [comment]
Fixed with https://github.com/m1/Env/pull/12
