### ISSUE TITLE
Single-quoted strings still parse variables

### ISSUE THREAD

**Issue by dccampbell** [m1/Env#2]
Ran into an interesting issue today whereby one specific environment would crash during dotenv parsing. I tracked it down to a specific line and eventually realized that one of the auto-generated salts in the .env had created a string containing `${` and `}`. Thus, the parser would crash as the gibberish in between the braces obviously matched no variable name.

The salt was single-quoted however, so this behavior is rather unexpected as it matches neither Bash nor PHP's parsing rules. I also noticed that despite the README having such a wide variety of examples, this edge-case is missing. Any parsing or expansion of variables should probably be disabled within single quote strings.

**Comment by m1** [comment]
Just to clarify, something like this: `KEY='${not a value}'` will crash?

**Comment by dccampbell** [comment]
Yes, in the same way it would if it's double-quoted or unquoted. 

Confirmed these cases:
:x: `KEY='${}'` (crash, unexpected)
:white_check_mark: `KEY="${}"` (crash, expected)
:x: `KEY='${NotAVar}'` (crash, unexpected)
:white_check_mark: `KEY="${NotAVar}"` (crash, expected)
:x: `KEY='foo_${NotAVar}_bar'` (crash, unexpected)
:white_check_mark: `KEY='${NotAVar'` (no crash, expected)
:x: `KEY='\${}'` (crash, unexpected)
:grey_question: `KEY="\${}"` (crash, expected?)

**Comment by m1** [comment]
How does https://github.com/m1/Env/commit/5e7b6c78a0f8027d63e98647803d8ddc9416cfcc look?

**Comment by dccampbell** [comment]
Tested again w/ the `ValueParser.php` from 5e7b6c7 and it fixed the issue. :+1:

**Comment by m1** [comment]
Nice :+1: -- will make a new release and thanks for bringing the issue to light.

**Comment by josegonzalez** [comment]
Heh this broke tests in `php-dotenv`, as I was incorrectly treating single-quotes as double :P

**Comment by m1** [comment]
Woops :scream:

**Comment by josegonzalez** [comment]
Whatever, it was a bug.
