### ISSUE TITLE
Parser chokes on line only containing spaces

### ISSUE THREAD

**Issue by sminnee** [m1/Env#7]
I had a file that worked with other .env parsers but failed with m1/env

The issue was a blank line containing only space characters. I agree that it's not a good style but it shouldn't break the parser.

**Comment by peter279k** [comment]
Hi @sminnee, thank you for your reply.

Could you reproduce this issue?

Could you provide the sample code and exception result?

Thanks.

**Comment by m1** [comment]
Fixed with https://github.com/m1/Env/pull/12

**Comment by sminnee** [comment]
Thanks! :-)
