### ISSUE TITLE
Changing visibility on Parser::doParse?

### ISSUE THREAD

**Issue by enygma** [m1/Env#8]
Is there any chance on changing the visibility of the `doParse` method in the `Parser` class from `private` to maybe just `protected`?

This would allow for a class extending the `Parser` to do fun things like set the `value_parser` property to something else and make the call to re-parse the configuration file.

I'm happy to make a PR for it too if that'd help...

**Comment by enygma** [comment]
nice! thanks! 👍

**Comment by enygma** [comment]
Oh, one other thing - think we could get a `2.1..1` release or something for this? Tagged releases are helpful :)

**Comment by m1** [comment]
Yep, done :smiley:

**Comment by enygma** [comment]
Woot! Thank you! 🤓
